platform :ios, '15.0' # Specify iOS version to Cocoa pods

target 'Flash Chat iOS13' do
  use_frameworks! # Necessary for Swift

  # Pods for Flash Chat iOS13
  pod 'CLTypingLabel', '~> 0.4.0'
  pod 'IQKeyboardManagerSwift', '6.5.0'
end
